- .gitignore
Makes working on a cloned instance used for hosting the site easier. I simply added the folders that appeared without making any modifications.
> Add generated content to .gitignore

- Website/structure-sources/index.rakudoc
It has been renamed to planet.raku.org, even though pl6anet is still hosted.
> Change URL of the blog aggregator

- Website/plugins/ogdenwebb/js/core.js
This change makes the site use the browser's preferred color scheme by default instead of always using light at first.
> feat: respect browser default theme

- .buildkite/archive.sh
- .buildkite/container.sh
- .buildkite/pipeline.yaml
- README.md
Consider this provisional.
It uses a Buildkite account as well as a Quay.io account that no one
else has access to. However, if merged, the following image will be
publicly-accessible and should be kept up to date on merges to main.
quay.io/colemanx/raku-doc-website:latest
I'd like to ask around the other community projects and see if there's
anything else to integrate with. In the meantime, this moves the ball
forward.
> Stub out Buildkite pipeline

- Website/plugins/ogdenwebb/js/core.js
- Website/plugins/ogdenwebb/ogdenwebb-replacements.raku
Proposed solution to https://github.com/Raku/doc-website/issues/52 .
Rather than relying on the asyncronous "i to svg" transformation, let's use the Javascript API of FontAwesome to generate the right tags at the right place directly.
For me, it seems to work so far.
> Workaround for badly loading sidebar

- Website/configs/01-config.raku
- Website/plugins/ogdenwebb/ogdenwebb-replacements.raku
As suggested in discussion in #68.
You will note that a) a change is made in the template for the Navigation bar, and b) the structure-source file that accesses the data is 'ignored' in the configuration data. Reversing the change is similarly a minimal change.
> temporarily disable extended search page for first launch

- .buildkite/pipeline.yaml
The `if` conditional was preventing a container build if the pipeline was triggered by a cron job. Remove that conditional so we publish a new container hourly.
> Build container if it's a scheduled build

- META6.json
- README.md
Part of #15; Remove warning. I haven't seen this failure mode; if needed we can add a note that cro themselves recommend installing without running the tests.
> Add cro as dep

- Website/plugins/cro-app/cro-run.raku
Since most terminals recognise URLs and offer to open them on click, include an `http` scheme in the initial status message.
> Include a scheme in the cro-run status message

- Website/structure-sources/about.rakudoc
It seems that there was some confusion and I was added by mistake. That list seems to be of important contributors to the website itself, which I am not.
Related to #129.
> Remove myself from the about page

- Website/configs/02-plugins.raku
- Website/plugins/git-reflog/cleanup.raku
- Website/plugins/git-reflog/config.raku
- Website/plugins/git-reflog/reflog.raku
git-reflog generates a template file that changes each time a source is changed. This removes the old template file.
> add cleanup to reflog

- Website/configs/01-config.raku
- Website/plugins/ogdenwebb/ogdenwebb-replacements.raku
Extended-search was in drop-down and would 404, Following @Altai-man , adding a link to this repo under More so that an issue with the site can be reported. Removing error-fixing page from the production site.
> remove extended search and error-report, add website issue reporting

- .buildkite/container.sh
- Caddyfile
This might seem like a drastic change, but it's really not a big
deal, since we aren't using advanced configs anyways.
Caddy's configuration language is much saner for our use-case, and
it even opens the door to api-based config.
> Add rewrites for .html; switch to caddy

- Caddyfile
go live only supported /Proc/Async, this restores the old functionality - many links to the docs depend on this style.
Part of #149
> Support old-style Proc::Async URLs

- Website/plugins/gather-css/css-collator.raku
- Website/plugins/ogdenwebb/core.js
Refactored how themes work: before it used name matching in js, after the change `gather-css/css-collator.raku` is used to attach theme name.
Js was refactored to only touch `link` tags that have `title` property attached to them, while allowing to add more themes more dynamically.
resolves #151
> add browser theme switching support

- Website/plugins/ogdenwebb/css/code/dark.css
- Website/plugins/ogdenwebb/css/code/light.css
- Website/plugins/ogdenwebb/css/main.css
- Website/plugins/ogdenwebb/css/themes/dark.css
- Website/plugins/ogdenwebb/css/themes/light.css
- Website/plugins/ogdenwebb/scss/code/_highlighting.scss
`.section` class padding currently interferes with the rendering of examples (see #144).
Explicitly set it to `0rem` within code blocks.
(This should apply to both light and dark themes.)
> Override CSS padding in `.raku-code` divs

- Website/configs/02-plugins.raku
disabling the plugin. It was providing information about which reflog the Raku/docs sources were coming from.
The information is low priority.
> disable git-reflog plugin

- .buildkite/pipeline.yaml
In non-interactive scenarios progress bars take up too much log space.
> Omit progress bars on CI

- Website/plugins/ogdenwebb/ogdenwebb-replacements.raku
- Website/structure-sources/license.rakudoc
Adds license page to structure, and makes License in the footer a link to the page remove redundant sections from template
> fixes #162

- Website/plugins/ogdenwebb/css/main.css
- Website/plugins/ogdenwebb/scss/code/_highlighting.scss
`.control` spans are currently styled with a font-size of `1rem`; in code blocks, inherit the size from `pre` instead.
An example of inconsistent sizing can be found on https://docs.raku.org/language/control.html#for (though it's prevalent across the site).
> Use consistent font size for highlighted control keywords

- META6.json
@cfa had found an error in `Raku/doc` where `L<xx|yy>` markup with the same `yy` but different `xx` were being rendered with the first `xx`. This has been rectified in `Raku-pod-render`.
> Bump requirement of Raku-Pod-Render

- Website/plugins/link-error-test/let-templates.raku
- Website/plugins/listfiles/listf-templates.raku
- Website/plugins/ogdenwebb/ogdenwebb-replacements.raku
- Website/plugins/search-bar/add-search.raku
- Website/plugins/secondaries/README.rakudoc
- Website/plugins/secondaries/config.raku
- Website/plugins/secondaries/gen-secondaries.raku
- Website/plugins/secondaries/header-templates.raku
- Website/plugins/typegraph/add-type-graph.raku
- Website/plugins/typegraph/tp-template.raku
- Website/structure-sources/index.rakudoc
This PR removes all `.html` file extensions from rendered HTML pages (eg, in the header to each page, after the PR the html would be `<a href="/about">About</a>` instead of the current `<a href="/about.html">About<\a>`
tp-template.raku had an extra debug output that might mess up the build logs, but not the build
I have tested this in [new-raku](https://new-raku.finanalyst.org) and it does not break anything.
> addresses issue #228

- META6.json
v0.4.6 contains reporting of the source being processed when a error occurs.
> bump Collection version cf issue #236

- META6.json
- Website/plugins/typegraph/add-type-graph.raku
- Website/plugins/typegraph/tp-template.raku
Raku/doc-website is missing the generated svg typegraphs. They should be generated at build time by the plugin `Website/plugins/typegraph`. The original logic was disrupted because a file `.placeholder` was inserted to keep the directory. The logic has been changed. If there are no typegraphs they will be generated in the build environment.
> addresses #232 missing typegraphs.

- META6.json
- Website/configs/02-plugins.raku
- Website/plugins/generated/README.rakudoc
- Website/plugins/generated/block.raku
- Website/plugins/generated/config.raku
- Website/plugins/generated/generated.css
- Website/plugins/generated/get-commit-id.raku
- Website/plugins/generated/t/05-basic.rakutest
- Website/plugins/generated/template.raku
- Website/structure-sources/about.rakudoc
This PR adds a new plugin `Website/plugins/generated` and bumps minimum versions of `Collection` and `Pod::From::Cache`. `Pod::From::Cache` v0.5.0 has new method to deliver last commit-id for documents. `Collection` v0.15.1 makes the commit-id and date of render available for plugins. `generated` adds these data when the block `=generated` is included in a Rakudoc source. `About.rakudoc` is amended to use `=generated`.
A live version can be seen at [new-raku /About](https://new-raku.finanalyst.org/about)
> Addresses issue #238

- Website/plugins/generated/template.raku
A debug line was left in `template.raku` in plugin `generated`. The information leaks into the build logs, otherwise is harmless. This PR removes the offending line.
> Remove debug output left after PR #240

- Website/plugins/ogdenwebb/css/themes/dark.css
- Website/plugins/ogdenwebb/css/themes/light.css
- Website/plugins/ogdenwebb/ogdenwebb-replacements.raku
- Website/plugins/ogdenwebb/scss/themes/_themes-template-common.scss
Additions are needed to the CSS, and a change to the list template.
These are relatively minor changes to the CSS and templates. The effect will be seen in `language/pod`, the examples of multi level lists and definition lists.
> Unordered lists and defn lists were not being rendered properly

- Website/plugins/ogdenwebb/core.js
- Website/plugins/ogdenwebb/css/themes/dark.css
- Website/plugins/ogdenwebb/css/themes/light.css
- Website/plugins/ogdenwebb/ogdenwebb-replacements.raku
- Website/plugins/ogdenwebb/scss/themes/_themes-template-common.scss
The patch affect `Website/ogdenwebb` by 
- changing the template for block code to add a button, 
- adding the js code to core.js, and 
- adding CSS for the button (placing on top left of block). 
The JS has been tested for Firefox. Uses `execCommand`, which is deprecated because Firefox does not recognise all of Clipboard API. 
This took a while to get a copy that would remove all HTML but respect whitespace. 
MINOR change to `lists` CSS to align bullets with left margin.
> addresses issue #244 adds a copy button to code blocks

- Website/templates/01-default.raku
This should fix #254 Links were being generated with an .html when link was to an target within a file.
This patch works on new-raku.
> Link urls were being generated with '.html'

- Website/templates/01-default.raku
`=next` and `=input` should be included in the generic templates. `=nested` is used in the existing pod.rakudoc file
> Add previously undocumented blocks to generic templates

- .buildkite/pipeline.yaml
This was incorrect and does not actually test for the presence
of the highlighter tooling.
> Revert assertion

- Website/plugins/ogdenwebb/config.raku
- Website/plugins/ogdenwebb/core.js
- Website/plugins/ogdenwebb/css/themes/dark.css
- Website/plugins/ogdenwebb/css/themes/light.css
- Website/plugins/ogdenwebb/ogdenwebb-replacements.raku
- Website/plugins/ogdenwebb/scss/themes/_themes-template-common.scss
Fixes #199 (which was reduced IMHO to highlighting other languages properly)
@lizmat @cfa @2colours @Altai-man @AlexDaniel  I think you have all commented on syntax highlighting at some point. 
Prior to this Patch, all code in code-blocks was sent to the Raku highlighter. Since all block codes are now labelled with a `:lang`, the renderer should send other languages to an appropriate highlighter.
Rather than re-invent the wheel, this Patch pulls in [Highlight-js](https://highlightjs.org/) to handle all languages other than Raku. (A Raku plugin for Highlight-js was started but not finished).
If a code-block has a `:lang<xxx>` where xxx is not Raku or Rakudoc, then Highlight-js is invoked to highlight it. Otherwise, the existing Raku syntax highlighter is used.
The new setup is running in …
> Adds highlights-js syntax coloring for non-Raku langs

- Website/configs/02-plugins.raku
- Website/plugins/filtered-toc/README.rakudoc
- Website/plugins/filtered-toc/config.raku
- Website/plugins/filtered-toc/css/filtered-toc-dark.css
- Website/plugins/filtered-toc/css/filtered-toc-light.css
- Website/plugins/filtered-toc/filtered-toc-template.raku
- Website/plugins/filtered-toc/filtered-toc.js
- Website/plugins/filtered-toc/scss/_filtered-toc-common.scss
- Website/plugins/filtered-toc/scss/_themes-colors.scss
- Website/plugins/filtered-toc/scss/filtered-toc-dark.scss
- Website/plugins/filtered-toc/scss/filtered-toc-light.scss
- Website/plugins/filtered-toc/t/05-basic.rakutest
- Website/plugins/ogdenwebb/core.js
This patch structurally has no effect on the build, but makes styling of the ToC easier. It will make the change to a different HTML setup easier. Visually, there **is** a change to the ToC. Four levels of heading are distinguished, instead of two.
> move ToC from ogdenwebb to filtered-toc plugin

- Website/plugins/secondaries/gen-secondaries.raku
both issues stem from the same problem: text is included in a secondary file from a primary file from a level2 heading. But the section is terminated by a level1 heading, not a level2 heading. The fix is to look for leveln, n-1, n-2, n-3 headings. By specification of RakuDoc, only headings upto level 4 are distinguished. The regex should be made more generic, perhpas by recursion on level, decrementing it to 0, but I don't know how.
> fixes issues #275 and #279

- Caddyfile
- README.md
- Website/configs/01-config.raku
- Website/configs/02-plugins.raku
- Website/configs/03-plugin-options.raku
- Website/plugins/cro-app/cro-run.raku
- Website/plugins/page-styling/page-styling.raku
- Website/plugins/raku-doc-setup/README.rakudoc
- Website/plugins/raku-doc-setup/add-deprecate.raku
- Website/plugins/raku-doc-setup/config.raku
- Website/plugins/raku-doc-setup/deprecated-urls
- Website/structure-sources/index.rakudoc
- Website/structure-sources/introduction.rakudoc
- Website/structure-sources/miscellaneous.rakudoc
- Website/structure-sources/reference.rakudoc
- repo_docs/README.rakudoc
three new top-level pages created from two previous ones
- introduction, from language
- reference from language
- miscellaneous, from programs and language
The navigation bar is changed accordingly, and tooltips (text available when hovering) added
The website index is modified accordingly
Using the `configs/01-config` mode-ignore, the old language and programs files are ignored, but left in the structure_files directory. They can be deleted later.
The `page-styling` plugin is amended so that the navigation bar is modified.
> completes issue #294

- Website/plugins/options-search/add-options-search.raku
- Website/plugins/options-search/config.raku
- Website/plugins/secondaries/config.raku
- Website/plugins/secondaries/gen-secondaries.raku
- Website/plugins/secondaries/t/15-gen-secondaries.rakutest
- searching for one of the above yields candidates that are named, eg.`routine/.`, but a page gets a 404.
- after some testing on various browsers/OS, it seems that those three specific character sequences cannot be used as filenames everywhere. Browsers/OS modify the URL before it reaches the server
- To overcome this behaviour, the three composite filenames `.` `..` `\` are mapped to URLs that will be preserved.
- This patch only affects three filenames and does not affect any other name.
- This problem was also present in the Documentable build of the website.
- patch changes `secondaries` plugin to create the url, and place the url in the podf structure. The `options-search` plugin is modified to pick up the url from the podf structure instead of forming the name by a rule.
> fix issue #288 problem searching for `\`,`.`,`..`

- Website/plugins/options-search/add-options-search.raku
- Headings in Composite files were being added to Search data, but composite files are themselves created from Primary headings, so headings in composite files are redundant.
- This patch filters them out of search data.
> fix issue #193

- Website/plugins/secondaries/header-templates.raku
- the source file `5to6-nutshell` contains the heading `C<constant>` that matches the regex looking for composite files, but this is a false positive as no name is generated
- this patch to the `Website/plugins/secondaries` verifies `.name` is non-blank.
> issue #309 reports a redundant link, patch removes it

- Website/configs/02-plugins.raku
- Website/configs/03-plugin-options.raku
- Website/plugins/sitemap/README.rakudoc
- Website/plugins/sitemap/config.raku
- Website/plugins/sitemap/make-sitemap.raku
- Website/plugins/sitemap/t/05-basic.rakutest
- new plugin for report stage (needs to be registered in render stage too to get options)
- generates `sitemap.xml` for SEO and puts it in html root directory
- (no other change needed as search engines pick up the file)
- change plugins config to add plugin
- change plugin-options config to add root-domain
- remove redundant plugin-options
- some priorities are given to files, which may affect their relative rankings in a search engines result response.
> new sitemap plugin completes issue #201

- Website/plugins/page-styling/page-styling.raku
Not adding 'table' template was an oversight when moving from 'ogdenweb' plugin to 'page-styling plugin'
> fix issue #307 compact tables

- Website/plugins/options-search/add-options-search.raku
The order of sections in search results was:
- Language
- Composite
- Class
- Role ...
Change the sort order to move Composite down below Class and Role because they both provide more relevant results.
> Move Composite below Class and Role in search results

- Website/plugins/options-search/options-search.js
When trying to use the search box, there was a significant delay between each char typed for the first couple of chars. Analyzing the time spent in Safari showed that when I typed 's' which had 3256 matches, 98% of the time was spent in style processing, i.e. rendering all of the results in the search results box. The only way to improve this is to reduce the number of entries we ever try to add.
Setting maxResults to 500 makes the search responsive and still delivers more results than is useful.
> Limit search results to 500

- Website/plugins/page-styling/css/page-styling-dark.css
- Website/plugins/page-styling/css/page-styling-light.css
- Website/plugins/page-styling/page-styling.raku
- Website/plugins/page-styling/scss/_themes-template-common.scss
- if an edit is needed, now there is no need to scroll to top of file
- move the div to the main tile
- restyle to make fairly unobtrusive
- z-index so it floats above text.
- opacity 50% so when overlapping, text is visible
> restyle page-edit button to fixed position when text scrolled

- Website/configs/02-plugins.raku
- Website/configs/03-plugin-options.raku
- Website/plugins/link-error-test/README.rakudoc
- Website/plugins/link-error-test/config.raku
- Website/plugins/link-error-test/let-callable.raku
- Website/plugins/link-error-test/let-templates.raku
- Website/plugins/secondaries/gen-secondaries.raku
- Website/structure-sources/about.rakudoc
- Link data is saved when parsing sources
- Target anchors created during rendering are saved
- LET compares link data and target data, and reports on mismatch
- The plugin was broken
- The format of the errors is converted into an HTML table and is better than the grid styling.
- A link to the error-report is placed in the About page.
> Link-error-test plugin finds unfulfilled links

- Website/plugins/secondaries/gen-secondaries.raku
- Composite pages are created from chunks of HTML in Primary pages from the start of Heading of some level eg `<h2` to the next heading of the same level or lower, eg `<h1`
- the regex was failing because it was generating `<h-1`
> fix bug in secondaries

- Website/structure-sources/types.rakudoc
The section for "Composite classes" on the https://docs.raku.org/types page is duplicated. This PR removes the second instance of it.
> Remove duplicate section for Composite classes

- Website/plugins/page-styling/css/page-styling-dark.css
- Website/plugins/page-styling/css/page-styling-light.css
- Website/plugins/page-styling/page-styling.raku
- Website/plugins/page-styling/scss/_themes-template-common.scss
- Website/plugins/page-styling/scss/page-styling-dark.scss
- Website/plugins/page-styling/scss/page-styling-light.scss
This is a rebased form of PR #330. 
Changes to page-styling, in the template for `X<>`
No tooltip.  Image shows `language/operators` page in docs.raku.org (left) and new-raku.finanalyst.org (right).
> Style terms that are indexed, but only in paragraphs, not in headings

- Website/plugins/options-search/css/options-search-dark.css
- Website/plugins/options-search/css/options-search-light.css
- Website/plugins/options-search/options-search-templates.raku
- Website/plugins/options-search/options-search.js
- Website/plugins/options-search/scss/_options-search-common.scss
- Website/plugins/page-styling/page-styling.js
A few experiments in this one PR as part of Issue #308. I'm interested in hearing any feedback about which option works better .
1. Changes the search binding from `Alt+F` to just `F` (more specifically lowercase `F`). I added a condition in the event listener to ensure the event target was from the document body. This prevents the event listener from swallowing the single characters that it matches while typing in the input field.
2. I added a binding in the search plugin to unfocus (or blur) the input field and close the search results when the `Escape` key is pressed.
3. Checked the `event.keyCode` against the unicode value for the bound character to fix `Alt` (aka `Option`) modifier to work on Mac. I'd rather move away from this approach because the `keyCode` property is deprecated …
> Exploring various options for keyboard shortcuts

- Website/plugins/page-styling/page-styling.raku
- adds edit crayon and content to both Composite and structure docs
- composite files get a popup suggesting how to edit source
- structure files get thrown to doc-website to edit structure source, similar to sources in `Raku/docs`
> resolves #338 edit content for all pages

- Website/plugins/options-search/add-options-search.raku
- `X<>` creates data that should be searchable
- currently it is part of the 'info' field
> resolves #206 adding indexed info into search value

- .gitignore
- Website/plugins/secondaries/header-templates.raku
- raku-doc-website.iml
- files of the form `syntax/qxx` were not being generated in doc-website, but were generated in new-raku.
- a secondary generation error occurred some time back, but the effect was only just noticed.
- fix is minor.
- minor change to .gitignore
- a Comma configuration file seeped from my workspace into repository, so deleted.
> fixes #346 missing syntax files

- Website/structure-sources/types.rakudoc
Built-in is correct as an adjective.
> Update types.rakudoc Built-in vs. Built in

- Website/plugins/filtered-toc/filtered-toc-template.raku
- Website/plugins/filtered-toc/filtered-toc.js
- Website/plugins/page-styling/config.raku
- Website/plugins/page-styling/css/page-styling-main.css
- Website/plugins/page-styling/page-styling.js
- Website/plugins/page-styling/page-styling.raku
- Website/plugins/page-styling/scss/page-styling-main.scss
- Indexed data is automatically collected, but was not used in the original website. I think this was a mistake.
- Not all pages have much indexing, but recently Issue Raku/doc#4440 shows that there is room for more.
- I have been running this patch on new-raku, and it is fairly useful on pages like [new-raku operators](https://new-raku.finanalyst.org/language/operators)
> resolves #345

- .buildkite/container.sh
- .buildkite/pipeline.yaml
On every push to a git branch called "docs-dev", a container tagged with "docs-dev" will be pushed, overwriting the existing image.
Commits to main (via PRs) will continue to publish to the "latest" tag.
Refs #75
> Publish a "docs-dev" tagged image

- EBook/configs/01-config.raku
- EBook/configs/02-plugins.raku
- EBook/configs/03-plugin-options.raku
- the aim of this node is to create an epub version of the Raku Documentation suite
- An epub can be described as a web site encapsulated into a file.
- See issue #356 for initial design goals.
> Start creating EBook mode

- Website/plugins/secondaries/config.raku
- Website/plugins/secondaries/gen-secondaries.raku
- Website/plugins/tablemanager/config.raku
- Website/plugins/tablemanager/tm-temps.raku
- Some routine names, eg `<?>`, were not HTML escaped
- The routines dataset was no generic enough
- Dataset created in *secondaries* and used in *tablemanager*
- Refactored secondaries and tablemanager plugins.
> Routines table had some incorrect escaping and hard-coded HTML

- Website/configs/02-plugins.raku
- Website/configs/03-plugin-options.raku
- Website/plugins/sqlite-db/README.rakudoc
- Website/plugins/sqlite-db/cleanup.raku
- Website/plugins/sqlite-db/compilation-callable.raku
- Website/plugins/sqlite-db/config.raku
- Website/plugins/sqlite-db/schema.sql
- Website/plugins/sqlite-db/t/05-basic.rakutest
- add sqlite-db plugin
- plugin accesses the dataset created for the Routines page in the website
- the data is formatted into the rows of an sqlite table
- the completed sqlite database is output into a filename specified in the `configs/03-plugin-options.raku` config file, so changing the value of the `db-filename` field of the `sqlite-db` sub-hash changes the output file name.
- the sqlite file is moved by Collection to a directory defined by 'database-dir' relative to the directory in which Collection runs. As set up here, the directory sqlite_dir will be at the same level as the existing renedered_html
> First step to issue #359, no change to the HTML output

- Website/plugins/options-search/options-search.js
- previous default was not to make them searchable (because too  many things were duplicated)
- the duplicates have now been reduced.
- users who have used the site before will need to remove the localstorage to over-ride the previous default.
> resolve issues #342 & #362 make indexed things searchable

- Website/plugins/options-search/config.raku
- Website/plugins/options-search/options-search-templates.raku
- Website/plugins/options-search/options-search.js
- add button to popup window in templates files
- separate defaults to be used twice
- add listener in js file
- after localStorage item is removed, a page refresh is forced to ensure variables and checkboxes are in sync.
- this does mean the modal is forced closed too.
> Fix Issue #368 reset button in search config

- Caddyfile
This will gzip responses from our webserver if the client indicates
support for it. All modern browsers do.
> Enable gzip compression in Caddyfile

- .buildkite/pipeline.yaml
- EBook/configs/03-plugin-options.raku
The build script drops the ebook file in our repository root. We can
move it into the rendered_html folder before archiving. This way, when
the archive is unpacked inside the container, it's located at the
expected root url.
The buildscript should be adjusted to put the ebook in rendered_html
at some point. But this hack works for now.
> Add EBook compilation to website build + container

- Website/plugins/page-styling/page-styling.raku
- removing tool-tips from page-styling
- remove disabling option from More
> when shortcuts disabled, the "tool-tips" were left in

- .buildkite/pipeline.yaml
This will allow passing the Ebook to other pipelines, just like we pass the tarball to other pipelines.
The Ebook is contained within the tarball now, so it's not strictly necessary, but it costs us nothing and should be more convenient for CI scripts.
> Upload ebook to Buildkite temp storage

- EBook/configs/01-config.raku
not needed for EBook, and will cause errors when EBook build tries to process `=Note` blocks
> ignore announcements.rakudoc when compiling EBook

- Caddyfile
Introduce an env var configuration: PROD=true
If that is NOT set, then respond to robots.txt with a file that
asks crawlers to stop indexing our site.
I will add this config to production once it lands.
> Prevent crawlers from indexing non-prod sites

- Website/plugins/raku-doc-setup/deprecated-urls
Caddy silently rewrites the first item in the amended file to the second. So any outside request is just redirected. I'm not sure we need to generate a 3xx redirect. If that's really important, a deeper dive into Caddy will be needed.
> resolves #387

- .buildkite/pipeline.yaml
We need an out-of-tree cache dir for svg files. A symlink to this will need to be created.
> test creating cache dir

- Website/plugins/hiliter/_highlighting.scss
- Website/plugins/hiliter/config.raku
- Website/plugins/hiliter/hiliter-dark.css
- Website/plugins/hiliter/hiliter-light.css
- in a code box, the 'language' label was obscuring the contents of the code box it labelled
- code box contents were overflowing to right
- this patch does not change problem in #396
> addresses issue in #353 label obsuring inner div

- Website/plugins/filtered-toc/config.raku
- ToC filtering depends on fuzzysort library
- Library was updated to 3.0.0, changing API, breaking ToC filtering
- Previous version (2.0.4) available on different cdn
> addresses issue #407

- Website/plugins/link-error-test/let-callable.raku
- all typegraph headings have an id of typegraphrelations
- if a target contains this, the target is passed
- it will not work if the target is in an external file, so this test is too broad, but given the rarity of such a link, I think this fix is the best use of time
> addresses issue in #401 whitelists all links with typegraphs

- .buildkite/pipeline.yaml
- EBook/configs/02-plugins.raku
- EBook/plugins/rainbow/README.rakudoc
- EBook/plugins/rainbow/config.raku
- EBook/plugins/rainbow/css/rainbow-dark.css
- EBook/plugins/rainbow/css/rainbow-light.css
- EBook/plugins/rainbow/rainbow.js
- EBook/plugins/rainbow/scss/_rainbow-main.scss
- EBook/plugins/rainbow/scss/_themes-colors.scss
- EBook/plugins/rainbow/scss/_variables.scss
- EBook/plugins/rainbow/scss/rainbow-dark.scss
- EBook/plugins/rainbow/scss/rainbow-light.scss
- EBook/plugins/rainbow/t/05-basic.rakutest
- EBook/plugins/rainbow/template.raku
- META6.json
- Website/configs/02-plugins.raku
- Website/plugins/rainbow/README.rakudoc
- Website/plugins/rainbow/config.raku
- Website/plugins/rainbow/css/rainbow-dark.css
- Website/plugins/rainbow/css/rainbow-light.css
- Website/plugins/rainbow/rainbow.js
- Website/plugins/rainbow/scss/_rainbow-main.scss
- Website/plugins/rainbow/scss/_themes-colors.scss
- Website/plugins/rainbow/scss/_variables.scss
- Website/plugins/rainbow/scss/rainbow-dark.scss
- Website/plugins/rainbow/scss/rainbow-light.scss
- Website/plugins/rainbow/t/05-basic.rakutest
- Website/plugins/rainbow/template.raku
@coke @dontlaugh This new plugin uses @patrickbkr 's very new entirely Raku syntax highlighter (Rainbow).
1. The plugin removes the dependency on the atom-highlighter, which was written originally in coffeescript. 
2. In turn, the removal of atom-highlighter removes entirely the dependency on npm and a large number of other javascript dependency in a webpack. This is a major simplification for anyone wanting to install doc-website, but who does not have npm (or equivalent).
3. Rainbow offers more categories for coloration than the atom-highlighter:
- instead of variable, we now have scalar, array & hash
- three regex categories, where none existed before
- two pod (rakudoc) categories
- several delimiters
For the time being I have not differentiated between the variables and delimiters, …
> removes the syntax highlighting dependency on Net

- README.md
- repo_docs/README.rakudoc
We fix a typo and remove reference to the nodejs highlighter.
I also felt that the deployment section could be shortened to the
bare minimum: what happens on merges to main and how production is
updated.
> Update the README

- Caddyfile
We were relying on a server-side env var, but I think we
can just match on a host header instead.
On prod, don't serve /robots.txt
Otherwise, dev deployments serve a file that should prevent
search engine indexing.
> Serving robots.txt: match on prod host header
