Raku/doc-website

- Website/plugins/ogdenwebb/js/core.js
- use localStorage over cookies
- remove the unused theme(s) on site load
> Fix "toggle theme" in Javascript

- Website/structure-sources/about.rakudoc
That's how it was, AlexDaniel (and JJ as well) did original 2 rounds of feedback for the new UI.
> Correct description line

- Website/plugins/tablemanager/tm-dark.css
- Website/plugins/tablemanager/tm-dark.scss
- Website/plugins/tablemanager/tm-light.css
- Website/plugins/tablemanager/tm-light.scss
- Website/plugins/tablemanager/tm-styling.css
- Website/plugins/tablemanager/tm-styling.scss
Requested by @finanalyst on #33
> Fix-up styles for table manager to be more in line with site

- .gitignore
- README.md
Follow up on 1c1b0fc9bdd9c13ef3c7c16b3d51988ce2a9d90f
> Update OgdenWebb -> Website

- CREDITS
> Add first pass at CREDITS file

- Website/plugins/ogdenwebb/css/main.css
- Website/plugins/ogdenwebb/scss/base/_base.scss
- Website/plugins/ogdenwebb/scss/base/_layout.scss
Addresses: #35, and stops the gray line from appearing on desktop searching.
> Make searchbar work properly on all screen sizes

- Website/structure-sources/routines.rakudoc
> issue #58 add 9999 as equivalent to all in routines page

- Website/plugins/ogdenwebb/add-search.raku
> Issue #46 remove redundant info in search

- Website/plugins/ogdenwebb/css/code/light.css
- Website/plugins/ogdenwebb/css/main.css
- Website/plugins/ogdenwebb/scss/base/_base.scss
> Stop hovering effects on search categories, since you can't click them.

- Website/plugins/search-bar/_colors.scss
- Website/plugins/search-bar/config.raku
- Website/plugins/search-bar/search-bar-dark.css
- Website/plugins/search-bar/search-bar-dark.scss
- Website/plugins/search-bar/search-bar-light.css
- Website/plugins/search-bar/search-bar-light.scss
- Website/plugins/search-bar/search-temp.js
now using up and down cursor in the scroll bar will  move show which item is selected.
Functionality is shown in new-raku.finanalyst.org
> sort search items on build, add css to make cursor key action visible

- .gitignore
- Website/structure-sources/index.rakudoc
> Change to mastodon

- Website/plugins/ogdenwebb/css/main.css
- Website/plugins/ogdenwebb/ogdenwebb-replacements.raku
- Website/plugins/ogdenwebb/scss/base/_base.scss
- Website/plugins/ogdenwebb/scss/main.scss
Extra information can be viewed by clicking on drop-up box or hovering
> answers issue #88. Generated and license moved to modals

- Website/plugins/ogdenwebb/css/themes/dark.css
- Website/plugins/ogdenwebb/css/themes/light.css
- Website/plugins/ogdenwebb/scss/themes/_themes-template-common.scss
- Website/plugins/search-bar/_colors.scss
- Website/plugins/search-bar/config.raku
- Website/plugins/search-bar/search-bar-dark.css
- Website/plugins/search-bar/search-bar-dark.scss
- Website/plugins/search-bar/search-bar-light.css
- Website/plugins/search-bar/search-bar-light.scss
reduces interline space on the dropdown menu, makes the cursor line and hover line background the same
> Improve search styling

- Website/structure-sources/error-report.rakudoc
> fix error-report typo

- Website/structure-sources/index.rakudoc
> fix index page typo

- Website/structure-sources/index.rakudoc
> remove redundant downloadable link

- Website/plugins/search-bar/add-search.raku
- Website/plugins/search-bar/config.raku
- Website/plugins/secondaries/config.raku
- Website/plugins/secondaries/gen-secondaries.raku
The changes can be seen in [new-raku](https://new-raku.finanalyst.org)
The change also adds several categories like Role. A new category 'Composite' is added to differentiate pages that contain aggregated methods/routines/ etc from various files.
These were not differentiated before.
> addresses #105 modifies search data, adds to secondary pod-config-data

- Website/plugins/ogdenwebb/ogdenwebb-replacements.raku
related to #119 adds a footer popup
> Add Raku-tm to footer

- Website/plugins/ogdenwebb/ogdenwebb-replacements.raku
- Website/structure-sources/index.rakudoc
- Website/templates/01-default.raku
removed the sporadic ones in raku/doc - added some here to the main template.
> add more ™

- Website/plugins/search-bar/add-search.raku
- Website/plugins/search-bar/search-temp.js
addresses #128 .
@coke merging to test this works on docs-dev
> tie the search Google call to the hostname of the site.

- README.md
- Website/plugins/ogdenwebb/css/main.css
No changes to the underlying (S)CSS were made, other than rerunning
```
$ ./update-css ogdenwebb
```
with the Node version of `sass`.
> Document the correct `sass` version, refresh CSS

- Caddyfile
Right now we are logging very little
> Add more access logs

- Website/plugins/ogdenwebb/ogdenwebb-replacements.raku
work on this revealed html files were not being correctly terminated with </body></html> files. So this cleanup done here.
> addresses issue #177

- Website/plugins/secondaries/gen-secondaries.raku
> addresses issue #186

- Website/plugins/ogdenwebb/ogdenwebb-replacements.raku
its a trivial change to add a link.
> addresses issue #221 & #214

- Website/structure-sources/types.rakudoc
Actually this error was found when trying to resolve issue #231
The PR only affects the contents of one web page without changing anything else.
> Addresses issue #241 (missing Type categories)

- META6.json
- Website/plugins/ogdenwebb/ogdenwebb-replacements.raku
This is the second attempt at this fix. Waiting to see if the build passes.
> Addresses code-blocks with format codes. fixes #124

- Website/plugins/cro-app/config.raku
- Website/plugins/cro-app/cro-run.raku
Cro is not used for build, and only exists if someone wants to clone repo for local build and then serve those files.
> This PR updates the Cro-app for the secondary refactoring

- Website/plugins/secondaries/gen-secondaries.raku
The issue related to HTML escaped text in the `<title>...</title>` of `<head>`. So, the title is unescaped.
At the same time, the secondary files do not have Table of Contents, which Documentable used to include. So, that is fixed too.
The search function provides extra information for most categories, except for Composite files, so this information is now added.
The effect can be seen at [new-raku eg /routine/=>](https://new-raku.finanalyst.org/routine/=>)
> fixes issue #273

- Website/plugins/typegraph/add-type-graph.raku
- Website/plugins/typegraph/config.raku
- Website/plugins/typegraph/tp-template.raku
int is under native/int, and Int is under type/Int. Both docs have `:kind<Type>`
> Attach typegraphs to kind<Type>

- Website/configs/02-plugins.raku
rebased enabling patch effect of page-styling for a limited number of source files in docker image `finanalyst/new-raku-website:dev`
> enable page-styling in place of ogden-webb

- Website/plugins/font-awesome/config.raku
- Website/plugins/generated/t/05-basic.rakutest
- Website/plugins/hiliter/config.raku
- Website/plugins/hiliter/t/05-basic.rakutest
- Website/plugins/listfiles/t/10-more.rakutest
- Website/plugins/search-bar/t/05-basic.rakutest
- Website/plugins/secondaries/t/test-temps.rakuon
- Website/plugins/tablemanager/t/05-basic.rakutest
- some doc-website plugins had become out-of-sync with Collection plugins, particularly in relation to the custom test module
- two plugin tests failed because of recent changes, so tests needed to be updated to reflect changes in the plugin output.
> addresses test-related problems in issue #304 (no change to build)

- Website/plugins/filtered-toc/config.raku
- Website/plugins/filtered-toc/css/filtered-toc-dark.css
- Website/plugins/filtered-toc/css/filtered-toc-light.css
- Website/plugins/filtered-toc/scss/_filtered-toc-common.scss
- Website/plugins/page-styling/config.raku
- Website/plugins/page-styling/css/page-styling-dark.css
- Website/plugins/page-styling/css/page-styling-light.css
- Website/plugins/page-styling/scss/_themes-template-common.scss
- in filtered-toc plugin, scss to add scrolling on headings only
- prevent title disappearing upwards
- in page-styling, scss remove scroll on main panel
- css generated from scss
> change CSS on panels to remove double scrollbar issue #300

- Website/plugins/page-styling/css/page-styling-dark.css
- Website/plugins/page-styling/css/page-styling-light.css
- Website/plugins/page-styling/scss/_themes-template-common.scss
@2colours can you verify that this change works for you. (I deploy to new-raku in a few minutes)
> change CSS to remove font ligatures, which affects `<->`, issue #315

- Website/plugins/page-styling/css/page-styling-dark.css
- Website/plugins/page-styling/css/page-styling-light.css
- Website/plugins/page-styling/page-styling.raku
- Website/plugins/page-styling/scss/_themes-template-common.scss
- change Bulma classes in page styling
- change main column width
- remove excess bottom margin
> fixes #341 bad tablet formating

- Website/plugins/page-styling/page-styling.js
@coke code section is commented out. I would prefer to leave the section in should we change out minds later if a better way emerges to handle all OS/browser combos emerges.
> This resolves issue #344

- Website/plugins/announcements/anouncement-templates.raku
- Website/plugins/announcements/config.raku
- Website/plugins/page-styling/config.raku
- Website/plugins/page-styling/css/centreToggle-dark.css
- Website/plugins/page-styling/css/centreToggle-light.css
- Website/plugins/page-styling/scss/_centreToggle.scss
- change colour of text
- make hover over background consistent
- green is not intutive for 'suppressed', so change to another pallet colour
- tweaks to placing of 'ball' & text
- remove redundant CSS (.original)
> make More->announcements less like link

- Website/configs/01-config.raku
@dontlaugh please review and authorise. Should have no effect on build, other than to produce report
- minor change in configs
- report can be accessed by `docs.raku.doc/error-report`
> addresses issue in Raku/docs #4476

- Website/plugins/page-styling/page-styling.raku
- turns out the fix is very simple, at least for desktop
- not sure how this will play on tablet or mobile formats
> addresses issue #410 simple CSS

- EBook/plugins/gather-css/README.rakudoc
- README.md
- Website/plugins/gather-css/README.rakudoc
- Website/plugins/gather-js-jq/README.rakudoc
- Website/plugins/listfiles/README.rakudoc
- Website/plugins/options-search/add-options-search.raku
- Website/plugins/search-bar/add-search.raku
- Website/plugins/secondaries/README.rakudoc
- Website/plugins/tablemanager/README.rakudoc
- Website/structure-sources/error-report.rakudoc
- config.raku
- repo_docs/README.rakudoc
Found with raku/doc spellcheck tests.
> Fix usage of "e.g."

- Website/structure-sources/about.rakudoc
old and AST renderings differ slightly with the spaces.
> whitespace cleanup

- Website/plugins/secondaries/gen-secondaries.raku
Add a '.' to top para of composite files
> Fix issue #422

- Website/plugins/secondaries/gen-secondaries.raku
Trying again to merge this 'docs-dev' into main. It is a minor change on the same line as the for #422.
> fix issue #421

- Website/plugins/page-styling/page-styling.raku
- Website/structure-sources/index.rakudoc
This changes contains superscripted ®
If feedback is that the R needs to be on same line, we can change that too
> Solves issue #426

- Website/structure-sources/index.rakudoc
I think we can comply with #426 with trademarks on the nav bar and the main subheading.
> One less R

- New_Website/L10N/add-ui-lang.rakumod
- New_Website/config/01-base.raku
- New_Website/config/02-plugins.raku
- New_Website/config/03-plugin-options.raku
- this patch creates a new directory, and stubs
- nothing in the new directory structure should affect the Collection
- the directory name New_Website ensures it will be ignored.
> Begin build-out of new website

- New_Website/L10N/add-ui-lang.rakumod
- New_Website/config/01-base.raku
- New_Website/config/02-plugins.raku
- New_Website/config/03-plugin-options.raku
- Website/plugins/page-styling/page-styling.raku
- Website/structure-sources/index.rakudoc
> reset docs-dev to main

- .github/workflows/build-docker.yml
- **Add registry login**
- **Add pushes to Quay if it's a commit to main**
- **Fix workflow yaml syntax**
> login to registry
